// Vietnamese administrative divisions data
export const vietnamProvinces = [
  { code: "01", name: "Thành phố Hà Nội", districts: [
    { code: "001", name: "Quận Ba Đình" },
    { code: "002", name: "Quận Hoàn Kiếm" },
    { code: "003", name: "Quận Hai Bà Trưng" },
    { code: "004", name: "Quận Đống Đa" },
    { code: "005", name: "Quận Cầu Giấy" },
    { code: "006", name: "Quận Tây Hồ" },
    { code: "007", name: "Quận Long Biên" },
    { code: "008", name: "Quận Thanh Xuân" },
    { code: "009", name: "Quận Hoàng Mai" },
    { code: "010", name: "Quận Hà Đông" },
    { code: "011", name: "Quận Sơn Tây" },
    { code: "012", name: "Quận Sóc Sơn" },
    { code: "013", name: "Quận Đông Anh" },
    { code: "014", name: "Quận Gia Lâm" },
    { code: "015", name: "Quận Mê Linh" },
    { code: "016", name: "Quận Bắc Từ Liêm" },
    { code: "017", name: "Quận Nam Từ Liêm" },
    { code: "018", name: "Huyện Phúc Thọ" },
    { code: "019", name: "Huyện Đan Phượng" },
    { code: "020", name: "Huyện Hoài Đức" },
    { code: "021", name: "Huyện Quốc Oai" },
    { code: "022", name: "Huyện Thạch Thất" },
    { code: "023", name: "Huyện Chương Mỹ" },
    { code: "024", name: "Huyện Thanh Oai" },
    { code: "025", name: "Huyện Thường Tín" },
    { code: "026", name: "Huyện Phú Xuyên" },
    { code: "027", name: "Huyện Mỹ Đức" },
    { code: "028", name: "Huyện Ứng Hòa" },
    { code: "029", name: "Huyện Thanh Trì" },
  ]},
  { code: "02", name: "Thành phố Hồ Chí Minh", districts: [
    { code: "001", name: "Quận 1" },
    { code: "002", name: "Quận 3" },
    { code: "003", name: "Quận 4" },
    { code: "004", name: "Quận 5" },
    { code: "005", name: "Quận 6" },
    { code: "006", name: "Quận 7" },
    { code: "007", name: "Quận 8" },
    { code: "008", name: "Quận 10" },
    { code: "009", name: "Quận 11" },
    { code: "010", name: "Quận 12" },
    { code: "011", name: "Quận Bình Thạnh" },
    { code: "012", name: "Quận Gò Vấp" },
    { code: "013", name: "Quận Bình Tân" },
    { code: "014", name: "Quận Tân Bình" },
    { code: "015", name: "Quận Tân Phú" },
    { code: "016", name: "Quận Phú Nhuận" },
    { code: "017", name: "Quận 2" },
    { code: "018", name: "Quận 9" },
    { code: "019", name: "Quận Thủ Đức" },
    { code: "020", name: "Quận Bình Thạnh" },
    { code: "021", name: "Huyện Bình Chánh" },
    { code: "022", name: "Huyện Hóc Môn" },
    { code: "023", name: "Huyện Củ Chi" },
    { code: "024", name: "Huyện Nhà Bè" },
    { code: "025", name: "Huyện Cần Giờ" },
  ]},
  { code: "03", name: "Tỉnh Đà Nẵng", districts: [
    { code: "001", name: "Quận Hải Châu" },
    { code: "002", name: "Quận Thanh Khê" },
    { code: "003", name: "Quận Sơn Trà" },
    { code: "004", name: "Quận Ngũ Hành Sơn" },
    { code: "005", name: "Quận Liên Chiểu" },
    { code: "006", name: "Quận Cẩm Lệ" },
    { code: "007", name: "Huyện Hoàng Sa" },
    { code: "008", name: "Huyện Trường Sa" },
  ]},
  { code: "04", name: "Tỉnh Hải Phòng", districts: [
    { code: "001", name: "Quận Hồng Bàng" },
    { code: "002", name: "Quận Ngô Quyền" },
    { code: "003", name: "Quận Lê Chân" },
    { code: "004", name: "Quận Kiến An" },
    { code: "005", name: "Quận Hải An" },
    { code: "006", name: "Quận Đồ Sơn" },
    { code: "007", name: "Quận Dương Kinh" },
    { code: "008", name: "Huyện An Dương" },
    { code: "009", name: "Huyện An Lão" },
    { code: "010", name: "Huyện Kiến Thụy" },
    { code: "011", name: "Huyện Tiên Lãng" },
    { code: "012", name: "Huyện Vĩnh Bảo" },
    { code: "013", name: "Huyện Cát Hải" },
    { code: "014", name: "Huyện Bạch Long Vĩ" },
    { code: "015", name: "Huyện Thủy Nguyên" },
  ]},
  { code: "05", name: "Tỉnh An Giang", districts: [
    { code: "001", name: "Thành phố Long Xuyên" },
    { code: "002", name: "Thành phố Châu Đốc" },
    { code: "003", name: "Thị xã Tân Châu" },
    { code: "004", name: "Huyện An Phú" },
    { code: "005", name: "Huyện Châu Phú" },
    { code: "006", name: "Huyện Châu Thành" },
    { code: "007", name: "Huyện Chợ Mới" },
    { code: "008", name: "Huyện Chợ Vĩnh" },
    { code: "009", name: "Huyện Phú Tân" },
    { code: "010", name: "Huyện Thoại Sơn" },
    { code: "011", name: "Huyện Tri Tôn" },
  ]},
  { code: "06", name: "Tỉnh Bà Rịa - Vũng Tàu", districts: [
    { code: "001", name: "Thành phố Vũng Tàu" },
    { code: "002", name: "Thành phố Bà Rịa" },
    { code: "003", name: "Thị xã Phú Mỹ" },
    { code: "004", name: "Huyện Châu Đức" },
    { code: "005", name: "Huyện Côn Đảo" },
    { code: "006", name: "Huyện Đất Đỏ" },
    { code: "007", name: "Huyện Long Điền" },
    { code: "008", name: "Huyện Tân Thành" },
    { code: "009", name: "Huyện Xuyên Mộc" },
  ]},
  { code: "07", name: "Tỉnh Bắc Giang", districts: [
    { code: "001", name: "Thành phố Bắc Giang" },
    { code: "002", name: "Huyện Lạng Giang" },
    { code: "003", name: "Huyện Lục Ngạn" },
    { code: "004", name: "Huyện Sơn Động" },
    { code: "005", name: "Huyện Lục Nam" },
    { code: "006", name: "Huyện Việt Yên" },
    { code: "007", name: "Huyện Yên Dũng" },
    { code: "008", name: "Huyện Hiệp Hòa" },
    { code: "009", name: "Huyện Tân Yên" },
    { code: "010", name: "Huyện Yên Thế" },
  ]},
  { code: "08", name: "Tỉnh Bắc Kạn", districts: [
    { code: "001", name: "Thành phố Bắc Kạn" },
    { code: "002", name: "Huyện Ba Bể" },
    { code: "003", name: "Huyện Bạch Thông" },
    { code: "004", name: "Huyện Chợ Đồn" },
    { code: "005", name: "Huyện Chợ Mới" },
    { code: "006", name: "Huyện Na Rì" },
    { code: "007", name: "Huyện Ngân Sơn" },
    { code: "008", name: "Huyện Pác Nặm" },
  ]},
  { code: "09", name: "Tỉnh Bạc Liêu", districts: [
    { code: "001", name: "Thành phố Bạc Liêu" },
    { code: "002", name: "Huyện Giá Rai" },
    { code: "003", name: "Huyện Đông Hải" },
    { code: "004", name: "Huyện Hòa Bình" },
    { code: "005", name: "Huyện Phước Long" },
    { code: "006", name: "Huyện Vĩnh Lợi" },
  ]},
  { code: "10", name: "Tỉnh Bắc Ninh", districts: [
    { code: "001", name: "Thành phố Bắc Ninh" },
    { code: "002", name: "Thị xã Từ Sơn" },
    { code: "003", name: "Huyện Gia Bình" },
    { code: "004", name: "Huyện Lương Tài" },
    { code: "005", name: "Huyện Quế Võ" },
    { code: "006", name: "Huyện Tiên Du" },
    { code: "007", name: "Huyện Thuận Thành" },
    { code: "008", name: "Huyện Yên Phong" },
  ]},
  { code: "11", name: "Tỉnh Bến Tre", districts: [
    { code: "001", name: "Thành phố Bến Tre" },
    { code: "002", name: "Huyện Ba Tri" },
    { code: "003", name: "Huyện Bình Đại" },
    { code: "004", name: "Huyện Châu Thành" },
    { code: "005", name: "Huyện Chợ Lách" },
    { code: "006", name: "Huyện Giồng Trôm" },
    { code: "007", name: "Huyện Mỏ Cày" },
    { code: "008", name: "Huyện Thạnh Phú" },
  ]},
  { code: "12", name: "Tỉnh Bình Định", districts: [
    { code: "001", name: "Thành phố Quy Nhơn" },
    { code: "002", name: "Thị xã An Nhơn" },
    { code: "003", name: "Huyện An Lão" },
    { code: "004", name: "Huyện Phù Cát" },
    { code: "005", name: "Huyện Phù Mỹ" },
    { code: "006", name: "Huyện Tuy Phước" },
    { code: "007", name: "Huyện Vĩnh Thạnh" },
    { code: "008", name: "Huyện Tây Sơn" },
    { code: "009", name: "Huyện Vân Canh" },
    { code: "010", name: "Huyện Hoài Nhơn" },
    { code: "011", name: "Huyện Hoài Ân" },
  ]},
  { code: "13", name: "Tỉnh Bình Dương", districts: [
    { code: "001", name: "Thành phố Thủ Dầu Một" },
    { code: "002", name: "Thị xã Dĩ An" },
    { code: "003", name: "Thị xã Bến Cát" },
    { code: "004", name: "Thị xã Tân Uyên" },
    { code: "005", name: "Huyện Bàu Bàng" },
    { code: "006", name: "Huyện Dầu Tiếng" },
    { code: "007", name: "Huyện Phú Giáo" },
    { code: "008", name: "Huyện Bắc Tân Uyên" },
  ]},
  { code: "14", name: "Tỉnh Bình Phước", districts: [
    { code: "001", name: "Thành phố Đồng Xoài" },
    { code: "002", name: "Thị xã Bình Long" },
    { code: "003", name: "Thị xã Phước Long" },
    { code: "004", name: "Huyện Bù Đăng" },
    { code: "005", name: "Huyện Bù Gia Mập" },
    { code: "006", name: "Huyện Chơn Thành" },
    { code: "007", name: "Huyện Đồng Phú" },
    { code: "008", name: "Huyện Hớn Mẫn" },
    { code: "009", name: "Huyện Lộc Ninh" },
    { code: "010", name: "Huyện Bù Rá" },
  ]},
  { code: "15", name: "Tỉnh Bình Thuận", districts: [
    { code: "001", name: "Thành phố Phan Thiết" },
    { code: "002", name: "Thị xã La Gi" },
    { code: "003", name: "Huyện Bắc Bình" },
    { code: "004", name: "Huyện Đức Linh" },
    { code: "005", name: "Huyện Hàm Tân" },
    { code: "006", name: "Huyện Hàm Thuận Bắc" },
    { code: "007", name: "Huyện Hàm Thuận Nam" },
    { code: "008", name: "Huyện Phú Quý" },
    { code: "009", name: "Huyện Tánh Linh" },
    { code: "010", name: "Huyện Tuy Phong" },
  ]},
  { code: "16", name: "Tỉnh Cà Mau", districts: [
    { code: "001", name: "Thành phố Cà Mau" },
    { code: "002", name: "Huyện Cái Nước" },
    { code: "003", name: "Huyện Cái Nước" },
    { code: "004", name: "Huyện Trần Văn Thời" },
    { code: "005", name: "Huyện U Minh" },
    { code: "006", name: "Huyện Thới Bình" },
    { code: "007", name: "Huyện Năm Căn" },
    { code: "008", name: "Huyện Ngọc Hiển" },
    { code: "009", name: "Huyện Đầm Dơi" },
  ]},
  { code: "17", name: "Tỉnh Cần Thơ", districts: [
    { code: "001", name: "Quận Ninh Kiều" },
    { code: "002", name: "Quận Bình Thủy" },
    { code: "003", name: "Quận Cái Răng" },
    { code: "004", name: "Quận Ô Môn" },
    { code: "005", name: "Quận Thốt Nốt" },
    { code: "006", name: "Huyện Cờ Đỏ" },
    { code: "007", name: "Huyện Vĩnh Thạnh" },
    { code: "008", name: "Huyện Thới Lai" },
  ]},
  { code: "18", name: "Tỉnh Cao Bằng", districts: [
    { code: "001", name: "Thành phố Cao Bằng" },
    { code: "002", name: "Huyện Bảo Lạc" },
    { code: "003", name: "Huyện Bảo Lâm" },
    { code: "004", name: "Huyện Hà Quảng" },
    { code: "005", name: "Huyện Hòa An" },
    { code: "006", name: "Huyện Nguyên Bình" },
    { code: "007", name: "Huyện Phục Hòa" },
    { code: "008", name: "Huyện Quảng Uyên" },
    { code: "009", name: "Huyện Trà Lĩnh" },
    { code: "010", name: "Huyện Trùng Khánh" },
    { code: "011", name: "Huyện Thạch An" },
    { code: "012", name: "Huyện Hà Lang" },
  ]},
]

// Helper functions
export function getProvinceByCode(code: string) {
  return vietnamProvinces.find(p => p.code === code)
}

export function getDistrictsByProvinceCode(provinceCode: string) {
  const province = getProvinceByCode(provinceCode)
  return province?.districts || []
}

export function getDistrictByCode(provinceCode: string, districtCode: string) {
  const districts = getDistrictsByProvinceCode(provinceCode)
  return districts.find(d => d.code === districtCode)
}
